### ISSUE TITLE
Adjust contrast

### ISSUE THREAD

**Issue by ClementCaporal** [LaboratoryOpticsBiosciences/napari-brainbow-diagnose#1]
## Pitch

Adapt the colormap to the brainbow depending on the dataset and all the different channels.
User should be able to visualize each channel histogram and:
- choose min and max of the color map.
- use a automatic (percentile?) [min max] finder
As a starting point, gamma shouldn't be changed.

## Additional context
For now, we can set the contrast using the napari interface
![image](https://user-images.githubusercontent.com/94049435/203513376-2a930af5-9a0a-4d62-946b-7b12b4b21437.png)
1. Drag the double slider to choose min max. If you use "right click" on one of the handles it opens 4.
2. Choose the min max as the min and max pixel value *on the current slide shown* (or the whole volume if the viewer is in 3D)
3. Choose the min max as the min and max pixel value *on the slide shown*
4. You can set manually the value with entering the number by hand. Allows also to see the actual value the slider allows you to choose. Can be open you use "right click" on one of the handles on 1.

## Alternative
- https://github.com/haesleinhuepf/napari-brightness-contrast#README.md

## Roadmap
- [x] Decide if we could not just take the plugin of Robert Haase. [The main problem is the size of our dataset](https://github.com/haesleinhuepf/napari-brightness-contrast/blob/592c529f4953fd1a2d50db056380297d69a5781b/napari_brightness_contrast/_dock_widget.py#L392)
- [ ] Create a branch `adjust_contrast`
- [ ] update the [adjust contrast file](https://github.com/LaboratoryOpticsBiosciences/napari-brainbow-diagnose/blob/hackathon_skel/src/napari_brainbow_diagnose/_contrast.py)
