### ISSUE TITLE
Explore brainbow through channel space

### ISSUE THREAD

**Issue by ClementCaporal** [LaboratoryOpticsBiosciences/napari-brainbow-diagnose#2]
## Pitch

The user should be able to visualize the image trough the channel space that in 3 channel brainbow can be seen as a rgb color cube Each pixel is a ratio of the different channel. We should observe cluster of ratio in the color space.
There exist multiple color spaces. To start, we would like to see the color space in a 3D cube with each axis corresponding to one channel.
![image](https://user-images.githubusercontent.com/94049435/203516504-d19ac142-32c0-4fc5-8276-f32c2cf07aa8.png)
Each pixel `p` with the channel `(r, g, b)` in this color space is one point localized in `(p_r, p_g, r_b)`.
The color space axis range should match either:
- [min max] of the whole brainbow image
- the [min max] in #1 
- 
## Additional context
Check quickly how the brainbow fluorescence is distributed. We aim to have clean clustered cone.

## Alternative
- @sbinnee or @ac744 you have notebook to show this kind of plot i think

## Roadmap
- [ ] create `channel_space` branch
- [ ] update [channel_space file](https://github.com/LaboratoryOpticsBiosciences/napari-brainbow-diagnose/blob/hackathon_skel/src/napari_brainbow_diagnose/_channel_space.py)
- [ ] Being able to adjust the range of the channel axis according to #1
