### ISSUE TITLE
Export all parameters to reuse them later

### ISSUE THREAD

**Issue by ClementCaporal** [LaboratoryOpticsBiosciences/napari-brainbow-diagnose#4]
## Motivation

This plugin will have several parameter to optimize the visualization and understanding of brainbow images (created for example in #1  )
We would like to save them to: 
- reuse them in this plugin later
- reuse them in other plugin/workflow

## Pitch
The user can enter a `file_path` where a file containing all the parameters are saved.
We should discuss what the file will look like in particular for the format:
- json
- csv <- I don't think it can be used for our problem
- yaml

## Alternative
- [napari worflow](https://www.nature.com/articles/s41467-019-09552-9) allows user to export workflow using [this function](https://github.com/haesleinhuepf/napari-workflows/blob/main/src/napari_workflows/_io_yaml_v1.py)

## Roadmap
- [ ] Create dedicated branch `parameters_io`
- [ ] Choose the format (I suggest yml)
- [ ] Choose the structure to save the parameters
- [ ] Create the format writer
- [ ] Create the format reader
  - [ ] Read format
  - [ ] Populate widget parameters values
- [ ] Create widget
  - [ ] Loading
  - [ ] Writing
